import type {
  AgentNodeData,
  ClassifyNodeData,
  Graph,
  GuardrailsNodeData,
  IfElseNodeData,
  MemoryNodeData,
  NodeKind,
  SkillNodeData,
} from '../types';

// Deterministic graph → Python codegen.
//
// The generated code is illustrative: it uses a plausible Anthropic Agents-SDK
// shape but symbols here are stylised. The README in the .zip clarifies that.

const py = (s: string) => s.replace(/[\\"]/g, (c) => '\\' + c);
const ident = (label: string) =>
  label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '') || 'agent';

export function generateCode(graph: Graph, agentTitle: string): string {
  const lines: string[] = [];
  const used = new Set<NodeKind>();

  // Inventory used kinds for the imports list.
  for (const n of graph.nodes) used.add(n.type);

  const imports: string[] = ['Anthropic'];
  if (used.has('agent') || used.has('subagent')) imports.push('Agent');
  if (used.has('subagent')) imports.push('Subagent');
  if (used.has('classify')) imports.push('Classify');
  if (used.has('ifelse')) imports.push('IfElse');
  if (used.has('while')) imports.push('While');
  if (used.has('approval')) imports.push('UserApproval');
  if (used.has('memory')) imports.push('MemoryStore');
  if (used.has('guardrails')) imports.push('Guardrails');
  if (used.has('mcp')) imports.push('MCP');
  if (used.has('fileSearch')) imports.push('FileSearch');
  if (used.has('skill')) imports.push('Skill');

  lines.push('"""');
  lines.push(`${agentTitle}`);
  lines.push('Generated by the Agent Builder prototype.');
  lines.push('');
  lines.push('NOTE: SDK symbols below are illustrative. The real Anthropic SDK');
  lines.push('exposes equivalent primitives — replace as needed.');
  lines.push('"""');
  lines.push('');
  lines.push(`from anthropic import ${imports[0]}`);
  if (imports.length > 1) {
    lines.push(`from anthropic.agents import ${imports.slice(1).join(', ')}`);
  }
  lines.push('');
  lines.push('client = Anthropic()');
  lines.push('');

  // Sub-resources first (memory, file search, guardrails, skills).
  const memories = graph.nodes.filter((n) => n.type === 'memory');
  for (const n of memories) {
    const d = n.data as MemoryNodeData;
    lines.push(
      `${ident(d.label)} = MemoryStore(name="${py(d.storeName)}")`
    );
  }
  if (memories.length) lines.push('');

  const fileSearches = graph.nodes.filter((n) => n.type === 'fileSearch');
  for (const n of fileSearches) {
    const d = n.data as { source: string; label: string };
    lines.push(
      `${ident(d.label)} = FileSearch(source="${py(d.source)}")`
    );
  }
  if (fileSearches.length) lines.push('');

  const guardrails = graph.nodes.filter((n) => n.type === 'guardrails');
  for (const n of guardrails) {
    const d = n.data as GuardrailsNodeData;
    lines.push(
      `${ident(d.label)} = Guardrails(rules=[${d.rules.map((r) => `"${py(r)}"`).join(', ')}])`
    );
  }
  if (guardrails.length) lines.push('');

  const skills = graph.nodes.filter((n) => n.type === 'skill');
  for (const n of skills) {
    const d = n.data as SkillNodeData;
    lines.push(
      `${ident(d.label)} = Skill(name="${py(d.label)}", description="${py(d.description)}")`
    );
  }
  if (skills.length) lines.push('');

  // Subagents next.
  const subagents = graph.nodes.filter((n) => n.type === 'subagent');
  for (const n of subagents) {
    const d = n.data as AgentNodeData;
    lines.push(`${ident(d.label)} = Subagent(`);
    lines.push(`    name="${py(d.label)}",`);
    lines.push(`    model="${d.model}",`);
    lines.push(`    prompt="""${py(d.prompt)}""",`);
    if (d.tools.length) {
      lines.push(`    tools=[${d.tools.map((t) => `"${py(t)}"`).join(', ')}],`);
    }
    lines.push(`)`);
    lines.push('');
  }

  // Lead agents.
  const agents = graph.nodes.filter((n) => n.type === 'agent');
  for (const n of agents) {
    const d = n.data as AgentNodeData;
    lines.push(`${ident(d.label)} = Agent(`);
    lines.push(`    name="${py(d.label)}",`);
    lines.push(`    model="${d.model}",`);
    lines.push(`    prompt="""${py(d.prompt)}""",`);
    if (d.tools.length) {
      lines.push(`    tools=[${d.tools.map((t) => `"${py(t)}"`).join(', ')}],`);
    }
    if (subagents.length > 0) {
      lines.push(
        `    subagents=[${subagents.map((s) => ident((s.data as AgentNodeData).label)).join(', ')}],`
      );
      lines.push(`    orchestration="parallel",`);
    }
    if (d.memoryRef) {
      const mem = graph.nodes.find((m) => m.id === d.memoryRef);
      if (mem) {
        const md = mem.data as MemoryNodeData;
        lines.push(`    memory=${ident(md.label)},`);
      }
    } else if (memories.length === 1) {
      const md = memories[0].data as MemoryNodeData;
      lines.push(`    memory=${ident(md.label)},`);
    }
    if (d.dreaming) lines.push(`    dreaming=True,`);
    if (guardrails.length) {
      lines.push(
        `    guardrails=${ident((guardrails[0].data as GuardrailsNodeData).label)},`
      );
    }
    lines.push(`)`);
    lines.push('');
  }

  // Classify / IfElse summary as a comment block (graph-level routing logic
  // is conceptually represented; in real SDK this would be encoded by edges).
  const classifies = graph.nodes.filter((n) => n.type === 'classify');
  for (const n of classifies) {
    const d = n.data as ClassifyNodeData;
    lines.push(`# Classify "${py(d.label)}"`);
    lines.push(`# routes: ${d.intents.join(' | ')}`);
    lines.push('');
  }

  const ifelses = graph.nodes.filter((n) => n.type === 'ifelse');
  for (const n of ifelses) {
    const d = n.data as IfElseNodeData;
    lines.push(`# IfElse "${py(d.label)}"`);
    lines.push(`# branches: ${d.branches.join(' | ')}`);
    lines.push('');
  }

  // Entry point.
  const lead = agents[0];
  if (lead) {
    const d = lead.data as AgentNodeData;
    lines.push('if __name__ == "__main__":');
    lines.push(
      `    result = ${ident(d.label)}.run(input="${py(sampleInput(agentTitle))}")`
    );
    lines.push('    print(result)');
  }

  return lines.join('\n');
}

function sampleInput(title: string): string {
  if (/travel/i.test(title)) return 'Plan a 5-day trip to Tokyo for 2 people in October';
  if (/support/i.test(title)) return 'My order #4421 never arrived; can you help?';
  if (/email|inbox/i.test(title)) return 'Draft a reply scheduling next Tuesday at 2pm';
  return 'Hello, world.';
}
