import JSZip from 'jszip';
import type { Graph } from '../types';
import { generateCode } from './codegen';

const README = (agentName: string) => `# ${agentName}

Generated by the **Anthropic Agent Builder prototype**. The Python below is illustrative — it uses a plausible Anthropic Agents-SDK shape but the symbols are stylised. Replace with the real SDK before running.

## Run locally

\`\`\`bash
python -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
cp .env.example .env
# add your ANTHROPIC_API_KEY to .env
python agent.py
\`\`\`

## Files

- \`agent.py\` — the agent definition
- \`requirements.txt\` — Python dependencies
- \`.env.example\` — environment variable template

> Prototype output for an Anthropic Growth PM take-home.
`;

const REQUIREMENTS = `anthropic>=0.40.0
python-dotenv>=1.0.0
`;

const ENV_EXAMPLE = `# Set this to your Claude API key
# Get one at https://console.anthropic.com/settings/keys
ANTHROPIC_API_KEY=
`;

export async function downloadAgentZip(graph: Graph, agentName: string) {
  const zip = new JSZip();
  const folder = zip.folder(slug(agentName));
  if (!folder) return;
  folder.file('agent.py', generateCode(graph, agentName));
  folder.file('README.md', README(agentName));
  folder.file('requirements.txt', REQUIREMENTS);
  folder.file('.env.example', ENV_EXAMPLE);

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${slug(agentName)}.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function slug(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'my-agent'
  );
}
